"""add content fields to projects

Revision ID: 07501e5b5e74
Revises: 25057e4b38a5
Create Date: 2026-06-05 10:03:39.948068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07501e5b5e74'
down_revision = '25057e4b38a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('full_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('video_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('gallery_images', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('tags')
        batch_op.drop_column('gallery_images')
        batch_op.drop_column('video_url')
        batch_op.drop_column('full_content')
        batch_op.drop_column('short_description')

    # ### end Alembic commands ###
