"""rename projects to contents

Revision ID: 9832dccc5771
Revises: 07501e5b5e74
Create Date: 2026-06-05 11:07:48.130226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9832dccc5771'
down_revision = '07501e5b5e74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_contents')
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('location', sa.Text(), nullable=True))
        batch_op.drop_column('address')
        batch_op.drop_column('employer_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employer_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('address', sa.TEXT(), nullable=True))
        batch_op.drop_column('location')
        batch_op.drop_column('source_name')

    op.create_table('_alembic_tmp_contents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=150), nullable=False),
    sa.Column('image_file', sa.VARCHAR(length=100), nullable=True),
    sa.Column('content_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('is_visible', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('short_description', sa.TEXT(), nullable=True),
    sa.Column('full_content', sa.TEXT(), nullable=True),
    sa.Column('video_url', sa.VARCHAR(length=200), nullable=True),
    sa.Column('gallery_images', sa.TEXT(), nullable=True),
    sa.Column('tags', sa.VARCHAR(length=200), nullable=True),
    sa.Column('source_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('location', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
